# Build and test the application

name: ".NET 10"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_VERSION: 10.0.x
      RELEASE_SUBDIR: net10.0

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0 #avoid shallow clone so nerdbank gitversioning can do its work, see https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore && dotnet tool restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput="TestResults/" /p:UseSourceLink=true

    - name: Generate coverage report
      run: dotnet tool run reportgenerator -- "-reports:${{ github.workspace }}\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\coverage.cobertura.xml" "-targetdir:${{ github.workspace }}\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\CoverageReport" "-reporttypes:Html;MarkdownSummaryGithub"

    - name: Publish coverage in build summary
      run: cat "tests/rogerbriggen.myDupFinderLibUnitTest/TestResults/CoverageReport/SummaryGithub.md" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Add comment to PR
      if: github.event_name == 'pull_request'
      run: gh pr comment $PR_NUMBER --edit-last --create-if-none --body-file "tests/rogerbriggen.myDupFinderLibUnitTest/TestResults/CoverageReport/SummaryGithub.md"
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v7
      with:
        name: CoverageReport
        path: ${{ github.workspace }}\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\CoverageReport\

    - name: Upload build artefact myDupFinder
      uses: actions/upload-artifact@v7
      with:
        name: myDupFinder
        path: D:\a\myDupFinder\myDupFinder\src\rogerbriggen.myDupFinder\bin\Release\${{ env.RELEASE_SUBDIR }}\

    - name: Upload build artefact myDupFinderUnitTest
      uses: actions/upload-artifact@v7
      with:
        name: myDupFinderLibUnitTest
        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\bin\Release\${{ env.RELEASE_SUBDIR }}\

    - name: Upload build artefact myDupFinderUnitTest TestResults
      uses: actions/upload-artifact@v7
      with:
        name: myDupFinderLibUnitTestCodeCoverage
        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\
