name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 #avoid shallow clone so nerdbank gitversioning can do its work, see https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=\"json,opencover,cobertura\" /p:CoverletOutput="TestResults/" /p:UseSourceLink=true
    - name: Upload build artefact myDupFinder
      uses: actions/upload-artifact@v2
      with:
        name: myDupFinder
        path: D:\a\myDupFinder\myDupFinder\src\rogerbriggen.myDupFinder\bin\Release\netcoreapp3.1\
    - name: Upload build artefact myDupFinderUnitTest
      uses: actions/upload-artifact@v2
      with:
        name: myDupFinderLibUnitTest
        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\bin\Release\netcoreapp3.1\
    - name: Upload build artefact myDupFinderUnitTest TestResults
      uses: actions/upload-artifact@v2
      with:
        name: myDupFinderLibUnitTestCodeCoverage
        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\
